(alias
 (name runtest)
 (deps (alias_rec all)))

(rule
 (deps (package rocq-simple-io))
 (action (with-stdout-to HelloWorld.out
  (run %{bin:rocq} c -I ../plugin -Q ../src SimpleIO %{dep:HelloWorld.v}))))

(rule (alias runtest)
 (action (diff HelloWorld.expected HelloWorld.out)))

(rule
 (deps (package rocq-simple-io))
 (action (with-stdout-to TestOcamlbuild.out
  (run %{bin:rocq} c -I ../plugin -Q ../src SimpleIO %{dep:TestOcamlbuild.v}))))

(rule (alias runtest)
 (action (diff TestOcamlbuild.expected TestOcamlbuild.out)))

(rule
 (deps (package rocq-simple-io))
 (action (with-stdout-to RunIO.out
  (run %{bin:rocq} c -I ../plugin -Q ../src SimpleIO %{dep:RunIO.v}))))

(rule (alias runtest)
 (action (diff RunIO.expected RunIO.out)))

(rule
 (deps (package rocq-simple-io))
 (action (with-stdout-to TestInt63.out
  (run %{bin:rocq} c -I ../plugin -Q ../src SimpleIO %{dep:TestInt63.v}))))

(rule (alias runtest)
 (action (diff TestInt63.expected TestInt63.out)))
