language: c
sudo: required
env:
  global:
  - THIS_PACKAGE=coq-simple-io
  - OPAMVERBOSE=1
  - OPAMYES=true
  - OPAMKEEPBUILDDIR=true
  - OPAMWITHTEST=true
  matrix:
  - OCAML_VERSION=4.05 COQ_VERSION="8.8.2"
  - OCAML_VERSION=4.07 COQ_VERSION="8.9.1"
  - OCAML_VERSION=4.07 COQ_VERSION="8.10.dev"
  - OCAML_VERSION=4.07 COQ_VERSION="dev"
matrix:
  fast_finish: true
  allow_failures:
    - os: osx
os:
  - linux
  - osx
cache:
  apt: true
  directories:
  - $HOME/.opam
  - $HOME/Library/Caches/Homebrew

before_install:
  # Install OCaml and opam
  - curl -L https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh | sh

install:
- eval $(opam config env)
- opam repo add coq-released https://coq.inria.fr/opam/released
- opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev
- opam repo add coq-core-dev https://coq.inria.fr/opam/core-dev
- opam pin add coq -k version $COQ_VERSION
- opam pin add $THIS_PACKAGE --kind=path . -n  # Make opam aware of our dependency constraints
- opam install $THIS_PACKAGE --deps-only -v
- opam list

script:
- set -e
- opam install $THIS_PACKAGE -v
- opam upgrade
- opam remove $THIS_PACKAGE -v

before_cache:
- if [ $TRAVIS_OS_NAME = osx ]; then brew cleanup; fi
- opam clean
