fullname: Simple IO
shortname: simple-io
action: true
ci_test_dependants:
  enabled: true
  packages: ['coq-itree-io', 'coq-quickchick', 'coq-freespec-ffi', 'coq-bonsai']
dune: true
tested_rocq_opam_versions:
- version: '9.0'
- version: 'dev'
