version: 2.1

jobs:
  test:
    parameters:
      coq:
        type: string
    docker:
      - image: <<parameters.coq>>
    resource_class: large
    environment:
      OPAMJOBS: 4
      OPAMVERBOSE: 1
      OPAMWITHTEST: true
      OPAMYES: true
      TERM: xterm
      DEPENDANTS: |
        coq-itree-io
        coq-quickchick
        coq-freespec-ffi
        coq-bonsai
    steps:
      - startup
      - build

commands:
  startup:
    steps:
    - checkout
    - run:
        name: Configure environment
        command: echo . ~/.profile >> $BASH_ENV
    - run:
        name: Install dependencies
        command: |
          opam update
          opam pin add --kind=path . -n  # Make opam aware of our dependency constraints
          opam install --deps-only .
          opam list
        no_output_timeout: 30m
  build:
    steps:
    - run:
        name: Build, test, and install
        command: opam install . -j4  # gets killed at -j 35 by default
    - run:
        name: Test dependants
        command: |
          for PACKAGE in $DEPENDANTS
          do DEPS_FAILED=false
             opam install --deps-only $PACKAGE || DEPS_FAILED=true
             ([ $DEPS_FAILED == true ] && echo Skipping $PACKAGE) || \
             (opam install -t $PACKAGE && echo Tested $PACKAGE)
          done
    - run:
        name: Uninstall and cleanup
        command: |
          opam uninstall .
          make clean
          ls -AGR -I .git

workflows:
  version: 2
  build:
    jobs:
      - test:
          name: 'Coq 8.12'
          coq: 'coqorg/coq:8.12-ocaml-4.11-flambda'
      - test:
          name: 'Coq 8.13'
          coq: 'coqorg/coq:8.13-ocaml-4.13-flambda'
      - test:
          name: 'Coq 8.14'
          coq: 'coqorg/coq:8.14-ocaml-4.14-flambda'
      - test:
          name: 'Coq 8.15'
          coq: 'coqorg/coq:8.15-ocaml-4.14-flambda'
      - test:
          name: 'Coq 8.16'
          coq: 'coqorg/coq:8.16'
      - test:
          name: 'Coq 8.17'
          coq: 'coqorg/coq:8.17'
      - test:
          name: 'Coq 8.18'
          coq: 'coqorg/coq:8.18'
      - test:
          name: 'Coq 8.19'
          coq: 'coqorg/coq:8.19'
      - test:
          name: 'Coq 8.20'
          coq: 'coqorg/coq:8.20'
      - test:
          name: 'Coq dev'
          coq: 'rocq/rocq-prover:dev'
