version: 2.1

jobs:
  test:
    parameters:
      coq:
        type: string
    docker:
      - image: coqorg/coq:<<parameters.coq>>
    environment:
      OPAMVERBOSE: 1
      OPAMWITHTEST: true
      OPAMYES: true
      TERM: xterm
      DEPENDANTS: |
        coq-itree-io
        coq-quickchick
        coq-freespec-ffi
        coq-bonsai
    steps:
      - startup
      - build

commands:
  startup:
    steps:
    - checkout
    - run:
        name: Pull submodules
        command: git submodule update --init
    - run:
        name: Configure environment
        command: echo . ~/.profile >> $BASH_ENV
    - run:
        name: Install dependencies
        command: |
          opam repo -a add coq-extra-dev https://coq.inria.fr/opam/extra-dev
          opam pin add --kind=path . -n  # Make opam aware of our dependency constraints
          opam install --deps-only .
    - run:
        name: List installed packages
        command: opam list
  build:
    steps:
    - run:
        name: Install
        command: opam install . -j4  # gets killed at -j 35 by default
    - run:
        name: Test
        command: make compat && sh ./testall.sh
    - run:
        name: Test dependants
        command: |
          for PACKAGE in $DEPENDANTS
          do DEPS_FAILED=false
             opam install --deps-only $PACKAGE || DEPS_FAILED=true
             ([ $DEPS_FAILED == true ] && echo Skipping $PACKAGE) || \
             (opam install -t $PACKAGE && echo Tested $PACKAGE)
          done
    - run:
        name: Uninstall
        command: opam uninstall .
    - run:
        name: Cleanup
        command: |
          make clean
          ls -AGR

workflows:
  version: 2
  build:
    jobs:
      - test:
          name: 'Coq 8.11'
          coq: '8.11-ocaml-4.10-flambda'
      - test:
          name: 'Coq 8.12'
          coq: '8.12-ocaml-4.10-flambda'
      - test:
          name: 'Coq 8.13'
          coq: '8.13-ocaml-4.12-flambda'
      - test:
          name: 'Coq 8.14'
          coq: '8.14-ocaml-4.12-flambda'
      - test:
          name: 'Coq 8.15'
          coq: '8.15-ocaml-4.12-flambda'
      - test:
          name: 'Coq dev'
          coq: 'dev-ocaml-4.12-flambda'
