version: 2.1

jobs:
  test:
    parameters:
      coq:
        type: string
    docker:
      - image: coqorg/coq:<<parameters.coq>>
    environment:
      OPAMVERBOSE: 1
      OPAMWITHTEST: true
      OPAMYES: true
      TERM: xterm
    steps:
      - startup
      - build

commands:
  startup:
    steps:
    - checkout
    - run:
        name: Pull submodules
        command: git submodule update --init
    - run:
        name: Configure environment
        command: echo . ~/.profile >> $BASH_ENV
    - run:
        name: Install dependencies
        command: |
          opam repo -a add coq-extra-dev https://coq.inria.fr/opam/extra-dev
          opam update
          opam pin add --kind=path . -n  # Make opam aware of our dependency constraints
          opam install --deps-only .
    - run:
        name: List installed packages
        command: opam list
  build:
    steps:
    - run:
        name: Build and test locally
        command: |
          make
          make test
    - run:
        name: Build, test, and install package
        command: opam install .
    - run:
        name: Uninstall package
        command: opam uninstall .
    - run:
        name: Cleanup local directory
        command: |
          make clean
          ls -AGR

workflows:
  version: 2
  build:
    jobs:
      - test:
          name: 'Coq 8.11'
          coq: '8.11'
      - test:
          name: 'Coq 8.12'
          coq: '8.12'
      - test:
          name: 'Coq 8.13'
          coq: '8.13'
      - test:
          name: 'Coq 8.14'
          coq: '8.14'
      - test:
          name: 'Coq 8.15'
          coq: '8.15'
      - test:
          name: 'Coq dev'
          coq: 'dev'
