version: 2.1

defaults: &defaults
  environment:
    OPAMVERBOSE: 1
    OPAMWITHTEST: true
    OPAMYES: true
    TERM: xterm

commands:
  startup:
    steps:
    - checkout
    - run:
        name: Pull submodules
        command: git submodule update --init
    - run:
        name: Configure environment
        command: echo . ~/.profile >> $BASH_ENV
    - run:
        name: Install dependencies
        command: |
          opam repo -a add coq-extra-dev https://coq.inria.fr/opam/extra-dev
          opam update
          opam pin add --kind=path . -n  # Make opam aware of our dependency constraints
          opam install --deps-only .
    - run:
        name: List installed packages
        command: opam list
  build:
    steps:
    - run:
        name: Build and test locally
        command: |
          make
          make test
    - run:
        name: Build, test, and install package
        command: opam install .
    - run:
        name: Uninstall package
        command: opam uninstall .
    - run:
        name: Cleanup local directory
        command: |
          make clean
          ls -AGR
  deploy:
    steps:
    - run:
        name: Build Documentation
        command: make html
    - run:
        name: Configure Git
        command: |
          git config --global core.autocrlf input
          git config --global user.name  "Yishuai Li"
          git config --global user.email "yishuai@cis.upenn.edu"
    - run:
        name: Deploy GitHub Pages
        command: |
          if [ -z "$CIRCLE_TAG" ]
          then TAG=$CIRCLE_BRANCH
          else TAG=$CIRCLE_TAG
          fi
          PAGES=$CIRCLE_PROJECT_REPONAME/$TAG
          if [ -z "$CIRCLE_PULL_REQUESTS" ]
          then git clone -b gh-pages --depth 1 $CIRCLE_REPOSITORY_URL
               rm -rf $PAGES/*
               mkdir -p $PAGES
               cp -LRf html/* $PAGES
               cd $CIRCLE_PROJECT_REPONAME
               git add .
               git commit -m "$TAG $CIRCLE_SHA1" || true
               git push
          fi

jobs:
  coq 8_8:
    <<: *defaults
    steps:
    - startup
    - build
    docker:
    - image: coqorg/coq:8.8
  coq 8_9:
    <<: *defaults
    steps:
    - startup
    - build
    docker:
    - image: coqorg/coq:8.9
  coq 8_10:
    <<: *defaults
    steps:
    - startup
    - build
    docker:
    - image: coqorg/coq:8.10
  coq dev:
    <<: *defaults
    steps:
    - startup
    - build
    docker:
    - image: coqorg/coq:dev

workflows:
  version: 2
  build:
    jobs:
    - coq 8_8:
        filters:
          branches:
            ignore: gh-pages
          tags:
            only: /^\d.*/
    - coq 8_9:
        filters:
          branches:
            ignore: gh-pages
          tags:
            only: /^\d.*/
    - coq 8_10:
        filters:
          branches:
            ignore: gh-pages
          tags:
            only: /^\d.*/
    - coq dev:
        filters:
          branches:
            ignore: gh-pages
          tags:
            only: /^\d.*/
